services:
  mongodb:
    image: mongo:7.0.25
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    environment:
      MONGO_URL_PROD: mongodb://admin:123456@mongodb:27017/todo-app?authSource=admin&retryWrites=true&w=majority
      BACKEND_PORT: 5000
      NODE_ENV: prod
    command: npm run start

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
